name: Build Yocto Images

on:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.machine }}/${{ matrix.image }}
    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'pull_request_target' && github.event.label.name == 'run-workflow')
    env:
      DL_DIR: /yocto/downloads
      SSTATE_DIR: /yocto/sstate-cache
      REPOS_DIR: /repos
      ARTIFACTS_DIR: /work/artifacts
    strategy:
      fail-fast: true
      matrix:
        machine:
          - beagley-ai
          - intel-corei7-64
          - t3-gem-o1
        image: [gemstone-image-rd]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build a yocto-builder Docker image
        run: |
          cd "$GITHUB_WORKSPACE/.github/workflows/yocto-builder"
          docker build -f Dockerfile -t yocto-builder .

      - name: Build the image
        run: |
          docker run --rm --security-opt apparmor=unconfined \
            --security-opt seccomp=unconfined \
            -v "$GITHUB_WORKSPACE:/work" \
            --env "MACHINE=${{ matrix.machine }}" \
            --env "IMAGE=${{ matrix.image }}" \
            --env "DL_DIR=$DL_DIR" \
            --env "SSTATE_DIR=$SSTATE_DIR" \
            --env "REPOS_DIR=$REPOS_DIR" \
            --env "ARTIFACTS_DIR=$ARTIFACTS_DIR" \
            --ulimit "nofile=1024:1048576" \
            yocto-builder \
            /entrypoint.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yocto-${{ matrix.machine }}-${{ matrix.image }}
          path: ${{ github.workspace }}/artifacts/${{ matrix.machine }}-${{ matrix.image }}
